// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

import Foundation

/// Common mailbox model represents a single JMAP or IMAP mailbox, folder or Gmail label.
public struct Mailbox: CustomStringConvertible, Hashable, Identifiable {
    /// Common mailbox adopts JMAP roles; extends IMAP mailboxes with best guess as a client convenience.
    public typealias Role = JMAP.Mailbox.Role

    /// Common mailbox adopts JMAP rights model.
    public typealias Rights = JMAP.Mailbox.Rights

    public let role: Role?
    public let rights: Rights
    public var name: String
    public var isSubscribed: Bool
    public let unreadEmails: Int?
    public let totalEmails: Int?

    public init(
        _ name: String,
        role: Role? = nil,
        rights: Rights = Rights(),
        isSubscribed: Bool = true,
        unreadEmails: Int? = nil,
        totalEmails: Int? = nil,
        id: String? = nil
    ) {
        self.role = role
        self.rights = rights
        self.name = name
        self.isSubscribed = isSubscribed
        self.unreadEmails = unreadEmails
        self.totalEmails = totalEmails
        self.id = id ?? UUID().uuidString(1)
    }

    // MARK: CustomStringConvertible
    public var description: String { name }

    // MARK: Identifiable
    public let id: String
}

extension Mailbox {
    init(_ mailbox: (IMAP.Mailbox, IMAP.Mailbox.Status?), id: String? = nil) {
        // IMAP mailboxes don't have stable, server-provided IDs, so an
        // autogenerated UUID is assigned to each mailbox at the
        // first LIST of each account session. The assigned UUID is
        // transferred at each IMAP mailbox re-LIST, keeping ID stable
        // for entire app session.
        self.init(
            mailbox.0.path.name.description,
            role: mailbox.0.path.suggestedRole,  // Map JMAP mailbox roles to IMAP mailboxes
            rights: mailbox.0.path.suggestedRights,  // Shim mailbox permissions until IMAP MYRIGHTS implemented
            isSubscribed: !mailbox.0.attributes.filter({ $0 == .subscribed }).isEmpty,
            unreadEmails: mailbox.1?.unseenCount,
            totalEmails: mailbox.1?.messageCount,
            id: id ?? UUID().uuidString(1)  // Transfer UUID or autogenenrate new one
        )
    }

    init(_ mailbox: JMAP.Mailbox) {
        self.init(
            mailbox.name,
            role: mailbox.role,
            rights: mailbox.rights,
            isSubscribed: mailbox.isSubscribed,
            unreadEmails: mailbox.unreadEmails,
            totalEmails: mailbox.totalEmails,
            id: mailbox.id
        )
    }
}

extension IMAP.Mailbox.Path {
    // Best guess at MYRIGHTS based only on mailbox role and Gmail path prefix
    var suggestedRights: Mailbox.Rights {
        // IMAP mailbox rights all default to true if MYRIGHTS is
        // unavailable from provider:
        // https://datatracker.ietf.org/doc/html/rfc8440
        if let pathSeparator, name.description.components(separatedBy: "\(pathSeparator)")[0].hasPrefix("[Gmail]") {
            // Gmail allows renaming and deleting label mailboxes, but
            // [Gmail]-prefixed internal folders can't be modified.
            return Mailbox.Rights(mayRename: false, mayDelete: false)
        }
        return Mailbox.Rights(mayRename: suggestedRole == nil, mayDelete: suggestedRole == nil)
    }

    // Best-guess mapping of JMAP mailbox roles to IMAP mailboxes
    var suggestedRole: Mailbox.Role? {
        let rawValue: String = lastPathComponent.lowercased().components(separatedBy: .whitespaces)[0]
        if let role: Mailbox.Role = Mailbox.Role(rawValue: rawValue) {
            return role
        } else if rawValue.hasPrefix("archived") {
            return .archive
        } else if rawValue.hasPrefix("spam") || rawValue.hasPrefix("junk") || rawValue.hasPrefix("bulk") {
            return .junk
        } else if rawValue.hasPrefix("deleted") {
            return .trash
        } else if rawValue.hasPrefix("draft") {
            return .drafts
        } else {
            return nil
        }
    }
}
